
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


hostname=ep-shy-mode-ani0vfit-pooler.c-6.us-east-1.aws.neon.tech
port=5432
database=neondb
username=neondb_owner
password=npg_azY9KodFV5xP
